### ISSUE TITLE
ScalaTest in compile scope

### ISSUE THREAD

**Issue by candtoro** [outworkers/diesel#6]
Is there any reason to have scalatest for diesel-engine in compile scope?

**Comment by alexflav23** [comment]
Hi @candtoro,

A big mistake, there should be no reason why that happens. It will be removed asap. Thank you for reporting this, it does indeed make no sense.

Regards,

**Comment by alexflav23** [comment]
Hi @candtoro,

This is fixed in `0.4.2`, we'll publish new versions of dependant libs to prevent this from being a problem further.

Regards.

**Comment by candtoro** [comment]
Thanks alex
